name: Convert ENV to YAML

on:
  push:
    branches: [main]

jobs:
  convert:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Critical for pushing changes
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Reset credentials to use GITHUB_TOKEN instead of default
          persist-credentials: false  

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install PyYAML

      - name: Run conversion script
        run: python convert_script.py

      - name: Commit and push YAML files
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Pass the token explicitly
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin "https://x-access-token:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
          git add CONVERTED_ENV_TO_YAML/
          git commit -m "Auto-commit converted YAML files" || echo "No changes to commit"
          git pull --rebase  # Avoid merge conflicts
          git push origin main